import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/layouts/Sidebar";
import { AccountProvider } from "@/contexts/AccountContext";
import "./globals.css";
import { AuthProvider } from "@/lib/session";
import { auth } from "@/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <AuthProvider session={session}>
          <AccountProvider>
            <Sidebar>
              <main className="lg:h-screen h-fit p-8 py-4">{children}</main>
            </Sidebar>
          </AccountProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
